# Generated by Django 5.0.6 on 2026-08-02 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="trainers/%Y/%m/"
                    ),
                ),
                ("specialization", models.CharField(max_length=150)),
                (
                    "experience",
                    models.CharField(
                        help_text='e.g. "9 yrs experience"', max_length=50
                    ),
                ),
                (
                    "certifications",
                    models.TextField(
                        blank=True, help_text="Comma-separated or free text."
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("facebook", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number (7-20 digits, may include +, spaces, dashes, or parentheses).",
                                regex="^\\+?[0-9\\s\\-()]{7,20}$",
                            )
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "trainers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="trainers_is_acti_114395_idx"
                    ),
                    models.Index(
                        fields=["specialization"], name="trainers_special_a27a27_idx"
                    ),
                ],
            },
        ),
    ]
