# Generated by Django 5.0.6 on 2026-08-02 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number (7-20 digits, may include +, spaces, dashes, or parentheses).",
                                regex="^\\+?[0-9\\s\\-()]{7,20}$",
                            )
                        ],
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "contact_messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="contact_mes_email_a7fb56_idx"),
                    models.Index(
                        fields=["created_at"], name="contact_mes_created_eb3e69_idx"
                    ),
                ],
            },
        ),
    ]
