# Generated by Django 5.0.6 on 2026-08-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery/%Y/%m/")),
                ("title", models.CharField(blank=True, max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("floor", "Gym Floor"),
                            ("classes", "Classes"),
                            ("equipment", "Equipment"),
                            ("events", "Events"),
                            ("facility", "Facility"),
                        ],
                        db_index=True,
                        default="floor",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "gallery_images",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="gallery_ima_categor_0df631_idx"
                    )
                ],
            },
        ),
    ]
